version: "3"

services:
  mysql:
    restart: unless-stopped
    image: mysql:8
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./.mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql